### ISSUE TITLE
Unable to connect to db - Name or service not known

### ISSUE THREAD

**Issue by Michael-073** [JeroenBoersma/docker-compose-development#128]
When trying to run the magento2 installer through the command line I am getting the error 

```SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known```

I've checked #99 and I don't think that applies here because the issue seems to be that i am unable to find the db container.

**Comment by gkopec** [comment]
I had a similar problem when DB container couldn't start. I checked by `docker ps` that percona container hasn't been created.
The same message shown when I tried to run PHP code (CLI) outside of the container.

**Comment by JeroenBoersma** [comment]
Have you tried turning it of and on again?

![image](https://media.giphy.com/media/DUtVdGeIU8lmo/giphy.gif)

**Comment by JeroenBoersma** [comment]
The more serious answer:

like @gkopec said, check if the `db` service is up

```
$ dev ps
....
dockerdev-db                  /docker-entrypoint.sh mysqld     Up      127.0.0.1:3306->3306/tcp                                                                            
....
# if down, check the logs
$ dev logs db
....
dockerdev-db     | 2020-09-08T11:55:26.273892Z 0 [Note] mysqld: ready for connections.                                                                                                                               
...
```
This should help debugging.

Most common problem is, that there was a db server runninng on your computer, port 3306 locally was occupied, and therefore the db server cannot start.

After you fixed that the password/defaults aren't set correctly.

So, I would say, start over...
Only proceed if you haven't fixed it yet.

```
$ dev down --remove-orphans
$ docker volume rm dockerdev-db-volume
# make sure no db server is running locally and run
$ dev setup
```

Let me know if that worked, otherwise please include some logging :heart:
