### ISSUE TITLE
Support for symbolically linked workspace directories

### ISSUE THREAD

**Issue by johmanx10** [JeroenBoersma/docker-compose-development#134]
### Premise
As a practice, to keep project runtimes and hosting agnostic of their code repositories, I keep my GIT repos stored under `~/git/<repository>`.

### Setup
To get the `php` command, exposed from `bin/php` in this repository, running correctly, I tried creating a project directory inside the `workspace` directory, that looks like this:

```
workspace/
├ test/
│ └ project/
│   └ htdocs/
│     ├ index.html
│     └ info.php
└ symbiont/
  └ workspace → /home/$USER/git/symbiont/
```

### Verify provided structure

The provided file structure works as expected.

```
% cd ~development/workspace/test/project
% php htdocs/info.php| head -n 2
```

Outputs:

```
Creating development_php74_run ... done
phpinfo()
PHP Version => 7.4.10
```

### Custom structure

When using a symbolic link, the following problem occurs:

```
% cd ~development/workspace/symbiont/workspace
% php bin/symbiont
```

Outputs:

```
Creating development_php74_run ... done
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"mkdir /data/symbiont/workspace: file exists\"": unknown
```

### Expected result

I would have expected to be able to run project code that is set up through symbolic links.

### Diagnosis

I have tried to look within the `bin/` directory of this repository for what could cause this problem. The only cause I could find was within the definition of the `projectpath` function in `bin/dev`. This adds the working directory `/data/symbiont/workspace`.

I have also tried simply running outside of the workspace directory. This results in the following output:

```
Creating development_php74_run ... done
Could not open input file: bin/symbiont
```

### Possible solution

Instead of simply mounting the `workspace` directory on `/data`, the result of `readlink -f $PWD` could be mounted on `/data/$DEV_PROJECTPATH` to support symbolically linked workspace paths within the container.

**Comment by JeroenBoersma** [comment]
Hi, thanks for mentioning this...
This won't work as expected because we only share `workspace` with out running containers, we don't want to expose the full home directory.

So inside a running container, the symlink will never reach it's destination. Because `/home/$USER` is inaccessible .
This is by design thought.

It is possible to put your workspace anywhere.
By default it mounts `development/workspace`

You can create a `~/projects` or whatever.
`dev down` first and do a `dev volume rm workspace` (just removes the mapping). head home `cd`
and `dev volume workspace projects` to make the workspace directory point to `~/projects`

The logic in directory translation is still `customer.project.localhost` -> `~/projects/customer/project/(pub|htdocs|..)`
This is done so you don't have to change your development stack every time you switch projects. It's also possible to make multiple projects communicate to each other.

**Comment by johmanx10** [comment]
I understand how my suggestion will not work. I'm sure I can make my setup
work with your suggestions.

Thanks for your time and understanding :)
