### ISSUE TITLE
Magento 2 barks for xdebug 3.0

### ISSUE THREAD

**Issue by IJOL** [JeroenBoersma/docker-compose-development#147]
Just trying your project ( what a bad bad name has this repository, it should named something fancy.. it's awesome for that boring boring name ), and magento2 barks for a deprecated xdebug method, xdebug_disable ( anyone knows or imagines why in the hell one needs to disable the damn xdebug !!!! ) not present and deprecated.. it should be very useful to have a set of PHP 7.2 upwards images with the older xdebug 2.0, just to have a more pleasant adventure for those grasping his way with this repo

**Comment by JeroenBoersma** [comment]
Hi @IJOL , thanks for the awesome feedback :-) You're not the  first one questioning the name(just wait and see, a team is working on that)

Fair point, I've also considered adding an `noop` function and preload it in PHP to make it compatible with xdebug 2.0.
The gain and pleasure you get from using xdebug 3.x and up is way bigger than falling back to the older version.

One tip to consider, the problem is in the Magento testing suite, they've fixed that upstream.
https://github.com/magento/magento2-functional-testing-framework/commit/e95fb10d3a55d72af5d60e07703d09201812599e.patch

You could load the `patch` already in your project if you are using `vaimo/composer-patches`
See https://github.com/vaimo/composer-patches#usage-json-declaration howto to this.

If you don't use the testing suite, you can also remove it fully!
`composer remove --dev magento/magento2-functional-testing-framework`

**Comment by IJOL** [comment]
Thanks Jeroen, glad to hear from you, thanks for the tips, are really
helpful, and yes that was the damn testing framework, getting rid of it
altogether as per your opos.. many thanks, keep on  the good work, I will
be posting some question ns in a separate issue, to try to get our use case
in the mainstream..


Saludos,
--------------------------------------------
Ignacio J.Ortega
skype:ignacioj.ortega

**Comment by JeroenBoersma** [comment]
Ciao, thanks for the nice words... I love when a plan comes together
