### ISSUE TITLE
Reminder: Implement DNSMASQ

### ISSUE THREAD

**Issue by Caroga** [JeroenBoersma/docker-compose-development#37]
As discussed with @JeroenBoersma at Slack it would be preferred to implement a docker DNS server to automatically resolve your project urls.
Also, this could be used as DNS server for internal communication, leaving out the extra configuration for container to container communication. E.g. when testing http connections in api's.
This is a reminder about doing so.

**Comment by JeroenBoersma** [comment]
If executed it'll be combined wiht #43

**Comment by JeroenBoersma** [comment]
So, we ran in a lot of problems with people running dnsmasq, since latest Linux distros are having trouble combining dnsmasq with NetworkManager.

Google claimed the `.dev` extension and today I only use `.localhost` which always resolves to localhost if your are using modern dns... Which is a lot faster and also the default we ship today, I vote for fully deprecating *dnsmasq* support in our documentation because I think we cannot support in long term with the different repositories handling this differently.

Feel free to re-open if you think otherwise!
