### ISSUE TITLE
empty MySQL password apparently equals to "root"

### ISSUE THREAD

**Issue by pquerner** [JeroenBoersma/docker-compose-development#57]
In my conf/mysql file I have set the password to be an empty string, but down the road its been switched to password "root" somewhere. That should be documented somewhere.

**Comment by Caroga** [comment]
Sure, will add this along with some other remarks.

**Comment by JeroenBoersma** [comment]
I cannot imagine this would happen out of-the-box, do you have a reference/poc on this?
otherwise it would be even more confusing.

Maybe you pulled the one where the file was existing, this was a 2 day window, but it could be :-)
Then the password should be 'yourpassword'

We use [Percona](https://hub.docker.com/_/percona/) as the base image, it isn't mentioned over there either.

You did know you can actually use a password and start with `bin/dev myroot` and it'll log you in as root with the root password?

With just mysql it'll try to log you in with the current username and a blank password.

Closing this for now because I think this isn't because of the setup, feel free to re-open at any time
