### ISSUE TITLE
global "dev" command spams cmd

### ISSUE THREAD

**Issue by pquerner** [JeroenBoersma/docker-compose-development#58]
I have added the output from "bin/dev profile" to my .bashrc file and when I use "dev myroot" for example I get spammed with docker output before and/or after the command is done:

```
dev myroot
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 12
Server version: 5.7.19-17 Percona Server (GPL), Release '17', Revision 'e19a6b7b73f'

Copyright (c) 2009-2017 Percona LLC and/or its affiliates
Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit;
Bye
Starting development_redis_1 ... done
Starting development_db_1 ... done
```

**Comment by JeroenBoersma** [comment]
Hi @pquerner thanks for bringing this up, we are aware of this.

I see this daily, looks like it's a new "feature" in docker-compose, still haven't figured out why this happens, it's also when not using the global commands

I hope this will be fixed in one of the next docker-compose releases.
Closing for now because it's not something we can fix atm

**Comment by JeroenBoersma** [comment]
As a reference the repository of [Docker compose](https://github.com/docker/compose/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen)
