### ISSUE TITLE
MySQL container has 100gb limit

### ISSUE THREAD

**Issue by peterjaap** [JeroenBoersma/docker-compose-development#67]
I got this error when starting mysql;

INTERNAL ERROR: cannot create temporary directory

After logging into the `development_db_1` container, I did this;

```
root@8c90e2d6a087:/# df -h
Filesystem                Size  Used Avail Use% Mounted on
none                       94G   94G  0M  100% /
tmpfs                      64M     0   64M   0% /dev
tmpfs                     7.8G     0  7.8G   0% /sys/fs/cgroup
shm                        64M     0   64M   0% /dev/shm
/dev/nvme0n1p3             94G   83G  6.6G  93% /etc/hosts
/home/peterjaap/.Private  844G  397G  404G  50% /etc/mysql/conf.d
tmpfs                     7.8G     0  7.8G   0% /sys/firmware
```

So I went to `/var/lib/mysql` and removed some bigger databases. But I have a 1TB disk in my computer and I'd like to increase the size of this container to at least 200gb.

**Comment by JeroenBoersma** [comment]
This is not a problem in docker or in this repository, your *root* filesystem on your host is 100G to.

Run `df -h` on your host and it will report the same for the `/` mount. If your system is running slow, it's because of lack on resources too.

Docker stores it's volumes in `/var/lib/docker` by default and probably your */home* partitio has the other 900G.

I would recommend to create a new named/mapped volume on the bigger partition, copy all MySQL data over, remove the original volume.

````bash

dev down
# In this repo directory
mkdir mysql

docker run --rm -v ${PWD}/mysql:/new -v dockerdev-mysql-volume:/old apline 'cp -rvp /old/* /new'
docker volume rm dockerdev-mysql-volume
docker volume create -o 'type=none' -o 'device='${PWD}'/mysql' -o 'o=bind' dockerdev-mysql-volume

dev up
```

Copy/paste commands line by line and check their outcome, didn't run this myself.

Now you'll enjoy your bigger disk.

**Comment by JeroenBoersma** [comment]
This is resolved as it was indeed no docker problem
